### ISSUE TITLE
Installation / Usage instructions do not work

### ISSUE THREAD

**Issue by skokenes** [stefanwalther/qix-graphql#19]
Attempting to follow the installation and usage instructions on the README to get started, docker-compose up fails because the compose file relies on an environment variable `QIX_ENGINE_VER:latest`:

from docker-compose.yml:
```
qix:
    container_name: qix
    image: "qlikcore/engine:${QIX_ENGINE_VER:latest}"
    command: [
      "-S", "DocumentDirectory=/docs",
      "-S", "AcceptEULA=yes"
    ]

```

**Comment by stefanwalther** [comment]
With the recent changes you actually have to do a 

```
$ QIX_ENGINE_VER=12.171.0 QIX_ACCEPT_EULA=yes docker-compose up
```

**Comment by skokenes** [comment]
Yes that worked for me! I'm going to close this

**Comment by stefanwalther** [comment]
Thx, great!
