### ISSUE TITLE
Why use Qlik if your using GraphQL

### ISSUE THREAD

**Issue by cookiejest** [stefanwalther/qix-graphql#53]
This probably sounds abit random but what extra value does qlik add to a project if your already using GraphQL? GraphQL is basically its own associative engine right? Im just struggling to think why would need Qlik if your already familliar with GraphQL.

**Comment by skokenes** [comment]
Hey Adam, actually GraphQL is not any sort of engine. It's a spec for an API format, in the same vein of REST and RPC. Qlik uses JSON-RPC today via WebSockets, but there are scenarios where other types of APIs could be useful for communicating with the engine. For example, @ralfbecher created a library called `q-risotto` that puts a REST API in front of the Engine. This project does something similar - it shows how you would create a GraphQL API in front of the Engine.

There are various pros and cons for RPC vs REST vs GraphQL - it all depends on what you are trying to accomplish. This article breaks it down nicely: https://blog.apisyouwonthate.com/understanding-rpc-rest-and-graphql-2f959aadebe7

**Comment by cookiejest** [comment]
Hey Speros,

Get what your saying, I’ve not used GraphQL before, thought it was some
kind of alternative to REST protocol that you write schema for - I just
assumed qlik did the same type of function, modelling data and outputting
the result.  😄.

I’m not particularly experience with GraphQL, so just trying to educate
myself abit more ;). I need to find a good experience not to try it on to
understand the value

**Comment by stefanwalther** [comment]
Fully agree with @skokenes comments!
